### ISSUE TITLE
polypath error on empty polygon

### ISSUE THREAD

**Issue by mdsumner** [r-gris/sfdct#7]
```
lsu <- st_simplify(lakesuperior,  dTolerance = 110)
plot(lsu)
```

Error in polypath(p_bind(x[[i]]), border = border[i], lty = lty[i], lwd = lwd[i], : unable to allocate memory (in GPath)

**Comment by pdbentley** [comment]
try adding preserveTopology = TRUE


`library(sfdct)
library(sf)
lsu <- st_simplify(lakesuperior,  dTolerance = 110, preserveTopology = TRUE)
plot(lsu)
`

**Comment by mdsumner** [comment]
Hey thanks, nice!  

```R
lsu <- st_simplify(lakesuperior,  dTolerance = 110, preserveTopology = TRUE)
lsu_tri <- ct_triangulate(lsu)
plot(st_geometry(lsu_tri), col = "grey")
```

I'll get back to this when I remember what I wanted in the first place. I'm not sure simplification is really needed, it was only to make it fast enough.

**Comment by mdsumner** [comment]
I remember, this is to become an rgl rendering of this: https://github.com/r-gris/polyggon/blob/master/figure/README-unnamed-chunk-23-1.png
